server:
  port: 8071
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Moligouan/Mediscreen
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
  profiles:
    active: git
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enable: true
    liveness-state:
      enable: true
  endpoint:
    health:
      probes:
        enable: true