server:
  port: 8761  # Port par défaut pour Eureka

spring:
  application:
    name: eurekaserver
  cloud:
    config:
      enabled: false

eureka:
  instance:
    hostname: localhost  # Hôte du serveur Eureka
  client:
    register-with-eureka: false  # Ce service ne s’enregistre pas lui-même
    fetch-registry: false  # Il ne récupère pas d'autres services
    service-url:
      defaultZone: http://localhost:8761/eureka/