server:
  port: 8060
spring:
  application:
    name: note
    datasource:
      url: jdbc:mysql://mongodb:27018/mongodb
      username: root
      password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#  sql:
#    init:
#      mode: always
#      schema-locations: classpath:db/schema.sql
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    healthcheck:
      enable: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 60