server:
  port: 8080
spring:
  application:
    name: patient
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    healthcheck:
      enable: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 60